from __future__ import annotations

import json
import os
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, BinaryIO
from uuid import uuid4

import pandas as pd

MAX_MODEL_BYTES = int(os.getenv("MODELXRAY_MAX_MODEL_BYTES", 50 * 1024 * 1024))
MAX_DATASET_BYTES = int(os.getenv("MODELXRAY_MAX_DATASET_BYTES", 100 * 1024 * 1024))
MAX_DATASET_ROWS = int(os.getenv("MODELXRAY_MAX_DATASET_ROWS", 250_000))
MAX_DATASET_COLUMNS = int(os.getenv("MODELXRAY_MAX_DATASET_COLUMNS", 256))
MAX_DATASET_CELLS = int(os.getenv("MODELXRAY_MAX_DATASET_CELLS", 10_000_000))
SUPPORTED_MODEL_SUFFIXES = {".joblib", ".pkl", ".pickle"}
SUPPORTED_DATASET_SUFFIXES = {".csv"}

# Asset IDs are generated by this store: MODEL-<12 hex> / DATA-<12 hex>.
# Anything else is invalid; this is also the path-traversal defense.
_ASSET_ID_PATTERN = re.compile(r"^(MODEL|DATA)-[0-9A-F]{12}$")


def is_valid_asset_id(asset_id: str) -> bool:
    return bool(_ASSET_ID_PATTERN.match(asset_id or ""))


@dataclass(frozen=True)
class StoredAsset:
    asset_id: str
    asset_type: str
    filename: str
    path: str
    size_bytes: int
    metadata: dict[str, Any]


class AssetError(ValueError):
    pass


class AssetStore:
    """Local artifact store for trusted uploads.

    Important: joblib/pickle deserialization can execute arbitrary Python code.
    Uploads are treated as *trusted artifacts*; deserialization happens only
    inside the isolated worker process, never in the API process. This is
    defense-in-depth, not a sandbox (see README security section).
    """

    def __init__(self, root: str | Path = "data/assets") -> None:
        self.root = Path(root)
        self.models_dir = self.root / "models"
        self.datasets_dir = self.root / "datasets"
        self.meta_dir = self.root / "metadata"
        for directory in (self.models_dir, self.datasets_dir, self.meta_dir):
            directory.mkdir(parents=True, exist_ok=True)

    def _metadata_path(self, asset_id: str) -> Path:
        if not is_valid_asset_id(asset_id):
            raise AssetError(
                f"Invalid asset id {asset_id!r}. Expected format: MODEL-<id> or DATA-<id>."
            )
        resolved = (self.meta_dir / f"{asset_id}.json").resolve()
        if self.meta_dir.resolve() not in resolved.parents:
            raise AssetError("Invalid asset id: path traversal detected.")
        return resolved

    def _write_metadata(self, asset: StoredAsset) -> None:
        self._metadata_path(asset.asset_id).write_text(
            json.dumps(asdict(asset), indent=2, default=str), encoding="utf-8"
        )

    def get(self, asset_id: str) -> StoredAsset | None:
        try:
            path = self._metadata_path(asset_id)
        except AssetError:
            return None
        if not path.exists():
            return None
        return StoredAsset(**json.loads(path.read_text(encoding="utf-8")))

    def save_model_bytes(self, filename: str, source: BinaryIO) -> StoredAsset:
        suffix = Path(filename).suffix.lower()
        if suffix not in SUPPORTED_MODEL_SUFFIXES:
            raise AssetError("Unsupported model format. Use .joblib, .pkl or .pickle.")
        asset_id = f"MODEL-{uuid4().hex[:12].upper()}"
        path = self.models_dir / f"{asset_id}{suffix}"
        size = _copy_limited(source, path, MAX_MODEL_BYTES)
        # IMPORTANT: do not deserialize pickle/joblib in the API process.
        # Uploaded bytes are inspected only by suffix/size here; model validation
        # and deserialization happen inside the isolated execution worker.
        metadata = {
            "model_type": "unknown_until_worker_validation",
            "classes": [],
            "supports_probabilities": None,
            "warning": (
                "Model deserialization occurs only inside the isolated worker. "
                "Do not treat pickle/joblib as a secure serialization format."
            ),
        }
        asset = StoredAsset(asset_id, "model", filename, str(path), size, metadata)
        self._write_metadata(asset)
        return asset

    def save_dataset_bytes(self, filename: str, source: BinaryIO) -> StoredAsset:
        suffix = Path(filename).suffix.lower()
        if suffix not in SUPPORTED_DATASET_SUFFIXES:
            raise AssetError("Unsupported dataset format. Accepted format: CSV only.")
        asset_id = f"DATA-{uuid4().hex[:12].upper()}"
        path = self.datasets_dir / f"{asset_id}{suffix}"
        size = _copy_limited(source, path, MAX_DATASET_BYTES)
        try:
            frame = pd.read_csv(path)
        except Exception as exc:
            path.unlink(missing_ok=True)
            raise AssetError(f"CSV could not be parsed: {exc}") from exc
        if frame.empty:
            path.unlink(missing_ok=True)
            raise AssetError("Dataset is empty.")
        max_rows = int(os.getenv("MODELXRAY_MAX_DATASET_ROWS", MAX_DATASET_ROWS))
        max_columns = int(os.getenv("MODELXRAY_MAX_DATASET_COLUMNS", MAX_DATASET_COLUMNS))
        max_cells = int(os.getenv("MODELXRAY_MAX_DATASET_CELLS", MAX_DATASET_CELLS))
        if len(frame) > max_rows:
            path.unlink(missing_ok=True)
            raise AssetError(f"Dataset exceeds the {max_rows:,}-row limit.")
        if len(frame.columns) > max_columns:
            path.unlink(missing_ok=True)
            raise AssetError(f"Dataset exceeds the {max_columns}-column limit.")
        if len(frame) * max(1, len(frame.columns)) > max_cells:
            path.unlink(missing_ok=True)
            raise AssetError("Dataset exceeds the maximum cell budget.")
        duplicate_columns = frame.columns[frame.columns.duplicated()].tolist()
        if duplicate_columns:
            path.unlink(missing_ok=True)
            raise AssetError(f"Dataset contains duplicate columns: {duplicate_columns}")

        # Feature manifest: the upload-time column order (minus target, which is
        # chosen at investigation time) is persisted as the schema contract for
        # models without feature_names_in_. Reordered re-uploads must match.
        feature_columns = [c for c in frame.columns.tolist()]
        metadata = {
            "rows": int(len(frame)),
            "columns": int(len(frame.columns)),
            "features": feature_columns,
            "feature_manifest": feature_columns,
            "numeric_features": frame.select_dtypes(include="number").columns.tolist(),
            "categorical_features": [c for c in frame.columns if c not in frame.select_dtypes(include="number").columns],
            "missing_cells": int(frame.isna().sum().sum()),
            "preview": frame.head(5).to_dict(orient="records"),
        }
        asset = StoredAsset(asset_id, "dataset", filename, str(path), size, metadata)
        self._write_metadata(asset)
        return asset


def _copy_limited(source: BinaryIO, destination: Path, max_bytes: int) -> int:
    total = 0
    with destination.open("wb") as target:
        while True:
            chunk = source.read(1024 * 1024)
            if not chunk:
                break
            total += len(chunk)
            if total > max_bytes:
                destination.unlink(missing_ok=True)
                raise AssetError(f"File exceeds the {max_bytes // (1024 * 1024)} MB upload limit.")
            target.write(chunk)
    return total
